### ISSUE TITLE
Changes in Json/Yaml/Xml/JavaScript/whatever

### ISSUE THREAD

**Issue by nkolytschew** [ozwolf-software/java-mongo-migrations#2]
Is there also a possibility to write ChangeSet as Script-File, e.g. JSON/YAML.

Using MongoTemplate and Pojos may cause in failing Migration-Scripts/Code, if you change, for example the name of an attribute.

**Comment by OzWolf** [comment]
This project is EOL and has been replaced by [mongoTrek](https://github.com/ozwolf-software/mongo-trek) which utilises a YAML migrations file in place of Pojo classes.
